name: run-tests

on: 
    push:
        branches:
            - main
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@2

            - name: Button test
              id: button-test
              run: | 
                  g++ -o test.exe test.cpp BoardButton.cpp BoardButtonTest.cpp Button.cpp ButtonTest.cpp -luser32 -lgdi32 -lopengl32 -lgdiplus -lShlwapi -ldwmapi -lstdc++fs -static -std=c++17
                  ./test.exe