name: run-tests

on: 
    push:
        branches:
            - main
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install g++
              run: |
                  sudo apt install g++
                  gcc -v

            - name: Install dependencies
              run: | 
                  sudo apt update
                  sudo apt -y install build-essential libglu1-mesa-dev libpng-dev

            - name: Button test
              id: button-test
              run: | 
                  g++ -o main main.cpp BoardButton.cpp BoardButtonTest.cpp Button.cpp ButtonTest.cpp -lX11 -lGL -lpthread -lpng -lstdc++fs -std=c++17
                  ./main