name: run-tests

on: 
    push:
        branches:
            - main
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up C++ environment
              uses: actions/setup-cpp@v1

            - name: Button test
              id: button-test
              run: | 
                  g++ -o ButtonTest ButtonTest.cpp
                  echo "\n\n\n"
                  ./ButtonTest