name: run-tests

on: 
    push:
        branches:
            - main
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1

            - name: install gcc
              run: | 
                  # Linux/Macos example
                  sudo npx setup-cpp --compiler llvm --cmake true --ninja true --ccache true --vcpkg 
                  source ~/.cpprc


            - name: Button test
              id: button-test
              run: | 
                  g++ -v
                  g++ ButtonTest.cpp -o ButtonTest.exe
                  ls
                  ./ButtonTest.exe
    