name: run-tests

on: 
    push:
        branches:
            - main
    
jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: msys
              uses: msys2/setup-msys2@v2
              with:
                msystem: UCRT64
                update: true
                install: git mingw-w64-ucrt-x86_64-gcc

            - name: Run tests
              id: tests
              run: | 
                  g++ -o test.exe `
                  test.cpp `
                  BoardButton.cpp `
                  BoardButtonTest.cpp `
                  Button.cpp `
                  ButtonTest.cpp `
                  -luser32 -lgdi32 -lopengl32 -lgdiplus -lShlwapi -ldwmapi -lstdc++fs -static -std=c++17
                  ./test.exe